In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from datetime import datetime
from pandas import Series
import warnings

In [3]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [4]:
train_original=train.copy()
test_original=test.copy()

In [5]:
train

ID          Datetime  Count
0          0  25-08-2012 00:00      8
1          1  25-08-2012 01:00      2
2          2  25-08-2012 02:00      6
3          3  25-08-2012 03:00      2
4          4  25-08-2012 04:00      2
...      ...               ...    ...
18283  18283  25-09-2014 19:00    868
18284  18284  25-09-2014 20:00    732
18285  18285  25-09-2014 21:00    702
18286  18286  25-09-2014 22:00    580
18287  18287  25-09-2014 23:00    534

[18288 rows x 3 columns]

In [6]:
test

ID          Datetime
0     18288  26-09-2014 00:00
1     18289  26-09-2014 01:00
2     18290  26-09-2014 02:00
3     18291  26-09-2014 03:00
4     18292  26-09-2014 04:00
...     ...               ...
5107  23395  26-04-2015 19:00
5108  23396  26-04-2015 20:00
5109  23397  26-04-2015 21:00
5110  23398  26-04-2015 22:00
5111  23399  26-04-2015 23:00

[5112 rows x 2 columns]

In [7]:
train.drop(columns='ID',inplace=True)
test.drop(columns='ID',inplace=True)

In [8]:
train

Datetime  Count
0      25-08-2012 00:00      8
1      25-08-2012 01:00      2
2      25-08-2012 02:00      6
3      25-08-2012 03:00      2
4      25-08-2012 04:00      2
...                 ...    ...
18283  25-09-2014 19:00    868
18284  25-09-2014 20:00    732
18285  25-09-2014 21:00    702
18286  25-09-2014 22:00    580
18287  25-09-2014 23:00    534

[18288 rows x 2 columns]

In [9]:
train.set_index('Datetime',inplace=True)
train

Count
Datetime               
25-08-2012 00:00      8
25-08-2012 01:00      2
25-08-2012 02:00      6
25-08-2012 03:00      2
25-08-2012 04:00      2
...                 ...
25-09-2014 19:00    868
25-09-2014 20:00    732
25-09-2014 21:00    702
25-09-2014 22:00    580
25-09-2014 23:00    534

[18288 rows x 1 columns]

In [10]:
train.isna().any()

Count    False
dtype: bool

In [11]:
X=train.values
X

array([[  8],
       [  2],
       [  6],
       ...,
       [702],
       [580],
       [534]], dtype=int64)

In [12]:
.75*len(train)

13716.0

In [14]:
X_train=X[:13716]
X_valid=X[13716:]
X_train.shape

(13716, 1)

In [15]:
X_valid.shape

(4572, 1)

In [16]:
from statsmodels.tsa.arima_model import ARIMA

In [17]:
model_arima = ARIMA(X_train,order=(9, 2, 0))
model_arima_fit = model_arima.fit()
print(model_arima_fit.aic)

130604.62322573984


In [18]:
predictions= model_arima_fit.forecast(steps=4572)[0]
predictions

array([   395.89704467,    440.74967136,    486.71871995, ...,
       259850.9654376 , 259916.0132348 , 259981.06464639])

In [19]:
X_valid

array([[296],
       [216],
       [226],
       ...,
       [702],
       [580],
       [534]], dtype=int64)

In [24]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [25]:
sqrt(mean_squared_error(X_valid,predictions))

144508.99495916048

In [27]:
import itertools
p=d=q=range(0,5)
pdq = list(itertools.product(p,d,q))
pdq

[(0, 0, 0),
 (0, 0, 1),
 (0, 0, 2),
 (0, 0, 3),
 (0, 0, 4),
 (0, 1, 0),
 (0, 1, 1),
 (0, 1, 2),
 (0, 1, 3),
 (0, 1, 4),
 (0, 2, 0),
 (0, 2, 1),
 (0, 2, 2),
 (0, 2, 3),
 (0, 2, 4),
 (0, 3, 0),
 (0, 3, 1),
 (0, 3, 2),
 (0, 3, 3),
 (0, 3, 4),
 (0, 4, 0),
 (0, 4, 1),
 (0, 4, 2),
 (0, 4, 3),
 (0, 4, 4),
 (1, 0, 0),
 (1, 0, 1),
 (1, 0, 2),
 (1, 0, 3),
 (1, 0, 4),
 (1, 1, 0),
 (1, 1, 1),
 (1, 1, 2),
 (1, 1, 3),
 (1, 1, 4),
 (1, 2, 0),
 (1, 2, 1),
 (1, 2, 2),
 (1, 2, 3),
 (1, 2, 4),
 (1, 3, 0),
 (1, 3, 1),
 (1, 3, 2),
 (1, 3, 3),
 (1, 3, 4),
 (1, 4, 0),
 (1, 4, 1),
 (1, 4, 2),
 (1, 4, 3),
 (1, 4, 4),
 (2, 0, 0),
 (2, 0, 1),
 (2, 0, 2),
 (2, 0, 3),
 (2, 0, 4),
 (2, 1, 0),
 (2, 1, 1),
 (2, 1, 2),
 (2, 1, 3),
 (2, 1, 4),
 (2, 2, 0),
 (2, 2, 1),
 (2, 2, 2),
 (2, 2, 3),
 (2, 2, 4),
 (2, 3, 0),
 (2, 3, 1),
 (2, 3, 2),
 (2, 3, 3),
 (2, 3, 4),
 (2, 4, 0),
 (2, 4, 1),
 (2, 4, 2),
 (2, 4, 3),
 (2, 4, 4),
 (3, 0, 0),
 (3, 0, 1),
 (3, 0, 2),
 (3, 0, 3),
 (3, 0, 4),
 (3, 1, 0),
 (3, 1, 1),
 (3, 1, 2),
 (3,

In [28]:
import warnings
warnings.filterwarnings('ignore')
for param in pdq:
    try:
        model_arima = ARIMA(X_train,order=param)
        model_arima_fit = model_arima.fit()
        print(param,model_arima_fit.aic)
    except:
        continue

(0, 0, 0) 160003.96356146556
(0, 0, 1) 147195.70262399802
(0, 0, 2) 140274.3861515582
(0, 0, 3) 136297.36920906426
(0, 0, 4) 134225.13414035947
(0, 1, 0) 128883.19002528867
(0, 1, 1) 128759.65067721941
(0, 1, 2) 128737.53870586141
(0, 1, 3) 128736.70444943524
(0, 1, 4) 128732.52518810483
(0, 2, 0) 139671.94216645445
(0, 2, 1) 128886.33255958383
(1, 0, 0) 128542.30752672945
(1, 0, 1) 128475.53372229374
(1, 0, 2) 128425.28064380214
(1, 0, 3) 128408.15235622402
(1, 0, 4) 128371.13807160719
(1, 1, 0) 128750.50225241944
(1, 1, 1) 127978.80917898573
(1, 1, 2) 127966.8980392605
(1, 1, 3) 127855.30290171951
(1, 1, 4) 127797.42445186315
(1, 2, 0) 134438.62580266414
(1, 2, 4) 128743.70701631132
(2, 0, 0) 128467.02028874677
(2, 0, 1) 128011.80278518886
(2, 0, 2) 127999.57710966194
(2, 0, 3) 127888.20072030497
(2, 0, 4) 127830.63065331112
(2, 1, 0) 128739.83113952682
(2, 1, 1) 127963.78363285019
(2, 1, 2) 127937.07640839877
(2, 1, 3) 127191.40036167772
(2, 1, 4) 127552.39574803274
(2, 2, 0) 132621

In [48]:
model_arima = ARIMA(X,order=(10,0,6))
model_arima_fit = model_arima.fit()
print(model_arima_fit.aic)

184476.85508458773


In [49]:
predictions= model_arima_fit.forecast(steps=5112)[0]
predictions

array([462.06414198, 402.57462191, 400.71448628, ..., 332.72937595,
       304.99410213, 271.11332314])

In [50]:
submission=pd.read_csv('Sample Solution.csv')
submission['Count']=predictions
submission.to_csv('ARIMA1.csv',index=False)